append unit test to lesson_4
akvise/golang-course pull request #5
Opened 2021-07-22 22:45 UTC by akvise

2021-07-23 05:00 UTC, rat6666 requested changes

2021-07-23 05:00 UTC, rat6666 commented on lesson_5/cmd/main_test.go
> +			name: "want to 27.0 value",
seems we want 24 here

2021-07-23 05:00 UTC, rat6666 commented on lesson_5/cmd/main.go
> +	resArea, _ := s.Area()
why is the error not being handled? you shoul check if err != nil {} else {}

2021-07-23 05:00 UTC, rat6666 commented on lesson_5/cmd/main.go
> +	if c.radius < 0 {
i think 0 is not valida value and we do not need to try to compute with zero (please  check and fix in all places, and for width and height too)

2021-07-24 07:15 UTC, rat6666 approved these changes

2021-07-27 07:50 UTC, dimonl approved these changes

2021-07-27 17:13 UTC, merged